Fixes bug because note is type none...
File ".\ankidown\importer.py", line 185, in setNote
    self.editor.tags.setText(note.stringTags().strip())
AttributeError: 'NoneType' object has no attribute 'stringTags'